<InputScreen>:
    name: 'input'
    FloatLayout:
        size_hint: None, None

    DPEAButton:
        #Go back button
        size: 100, 100
        center_x: root.width * 0.95
        center_y: root.height * 0.8
        color: 0.035, 0.152, 0.725, 1
        text: "Go back"
        on_press: root.transition_back()

    DPEAButton:
        id: input_btn_0
        size: 300, 100
        center_x: root.width * 0.15
        center_y: root.height * 0.8
        color: 0.035, 0.152, 0.725, 1
        text: "IN 0"
        on_press: root.selectIN0()

    DPEAButton:
        id: input_btn_1
        size: 300, 100
        center_x: root.width * 0.25
        center_y: root.height * 0.6
        color: 0.035, 0.152, 0.725, 1
        text: "IN 1"
        on_press: root.selectIN1()

    DPEAButton:
        id: input_btn_2
        size: 300, 100
        center_x: root.width * 0.35
        center_y: root.height * 0.4
        color: 0.035, 0.152, 0.725, 1
        text: "IN 2"
        on_press: root.selectIN2()

    DPEAButton:
        id: input_btn_3
        size: 300, 100
        center_x: root.width * 0.45
        center_y: root.height * 0.2
        color: 0.035, 0.152, 0.725, 1
        text: "IN 3"
        on_press: root.selectIN3()

    Label:
        # label for title
        text: 'Input Screen'
        font_size: 40
        center_x: root.width * 0.0
        y: root.height * 0.45
        color: 0.0, 0.0, 0.0, 1