<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: dp(20)
        spacing: dp(20)

        GridLayout:
            cols: 3
            rows: 3
            spacing: dp(6)
            padding: dp(6)
            size_hint: 1, 1

            DPEAButton:
                text: 'Digital Input'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(0)

            DPEAButton:
                text: 'Screen 1'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(1)

            DPEAButton:
                text: 'Screen 2'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(2)

            DPEAButton:
                text: 'Screen 3'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(3)

            DPEAButton:
                text: 'Screen 4'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(4)

            DPEAButton:
                text: 'Screen 5'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(5)

            DPEAButton:
                text: 'Screen 6'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(6)

            DPEAButton:
                text: 'Screen 7'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(7)

            DPEAButton:
                text: 'Screen 8'
                size_hint: 1, 1
                font_size: '18sp'
                on_press: root.open_screen(8)